"""empty message

Revision ID: 42bf268c7591
Revises: 
Create Date: 2023-10-17 14:07:33.593297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bf268c7591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gempa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=True),
    sa.Column('jam', sa.String(), nullable=True),
    sa.Column('dateTime', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('lintang', sa.String(), nullable=True),
    sa.Column('bujur', sa.String(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('kedalaman', sa.String(), nullable=True),
    sa.Column('wilayah', sa.String(), nullable=True),
    sa.Column('potensi', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('dirasakan', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gempa')
    # ### end Alembic commands ###
