"""empty message

Revision ID: b9e585c3686d
Revises: fa1daa18b6fe
Create Date: 2023-10-17 14:21:18.818150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e585c3686d'
down_revision = 'fa1daa18b6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gempa_dirasakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=True),
    sa.Column('jam', sa.String(), nullable=True),
    sa.Column('dateTime', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('lintang', sa.String(), nullable=True),
    sa.Column('bujur', sa.String(), nullable=True),
    sa.Column('magnitude', sa.Numeric(), nullable=True),
    sa.Column('kedalaman', sa.String(), nullable=True),
    sa.Column('wilayah', sa.String(), nullable=True),
    sa.Column('dirasakan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gempa_terkini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.String(), nullable=True),
    sa.Column('jam', sa.String(), nullable=True),
    sa.Column('dateTime', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=True),
    sa.Column('lintang', sa.String(), nullable=True),
    sa.Column('bujur', sa.String(), nullable=True),
    sa.Column('magnitude', sa.Numeric(), nullable=True),
    sa.Column('kedalaman', sa.String(), nullable=True),
    sa.Column('wilayah', sa.String(), nullable=True),
    sa.Column('potensi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gempa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gempa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tanggal', sa.VARCHAR(), nullable=True),
    sa.Column('jam', sa.VARCHAR(), nullable=True),
    sa.Column('dateTime', sa.VARCHAR(), nullable=True),
    sa.Column('coordinates', sa.VARCHAR(), nullable=True),
    sa.Column('lintang', sa.VARCHAR(), nullable=True),
    sa.Column('bujur', sa.VARCHAR(), nullable=True),
    sa.Column('magnitude', sa.FLOAT(), nullable=True),
    sa.Column('kedalaman', sa.VARCHAR(), nullable=True),
    sa.Column('wilayah', sa.VARCHAR(), nullable=True),
    sa.Column('potensi', sa.VARCHAR(), nullable=True),
    sa.Column('kategori', sa.VARCHAR(), nullable=True),
    sa.Column('dirasakan', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gempa_terkini')
    op.drop_table('gempa_dirasakan')
    # ### end Alembic commands ###
