"""empty message

Revision ID: fa1daa18b6fe
Revises: 42bf268c7591
Create Date: 2023-10-17 14:13:00.026654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1daa18b6fe'
down_revision = '42bf268c7591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gempa', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gempa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
